sudo: false
language: node_js
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
install:
  - npm install grunt-cli -g
  - npm install
cache:
  directories:
    - node_modules
